### ISSUE TITLE
Error: Couldn't find key

### ISSUE THREAD

**Issue by rloipfinger** [zachcheatham/ha-omada#107]
Version: 0.5.0 an 0.6.0-beta.1
HA: 2024.7.2
Everything up-to-date

HA-log gets spammed with this error (about 3-4 entries per second). The "key" is always the same.
I think, It is some old MAC (I x-ed the value for privacy reasons). But I do not find this address in any devices or entities.
How can I prevent the integration from polling it?

2024-07-13 15:23:59.670 ERROR (MainThread) [custom_components.omada.api.api] Couldn't find key: XX-XX-XX-XX-XX-X
2024-07-13 15:23:59.706 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update when dispatching 'omada-update-c66f1913fd48fe433201c8eaac2e4c4b': ()
Traceback (most recent call last):
  File "/config/custom_components/omada/switch.py", line 307, in async_update
    if ((is_on := self.entity_description.is_on_fn(self.controller.api, self._mac)) != self.is_on):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/omada/switch.py", line 129, in <lambda>
    is_on_fn=lambda api, mac: not api.known_clients[mac].block,
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'block'

**Comment by spry-salt** [comment]
Same problem.

**Comment by enrico-stronati** [comment]
Same for me.
I don't know and I don't have the MAC address logged form HA.
Any information about?

**Comment by zachcheatham** [comment]
Please let me know if you are still seeing this issue in the latest release.

**Comment by rloipfinger** [comment]
The issue is gone. 
Thanks!
