### ISSUE TITLE
Problems after controller update omada 5.0.30

### ISSUE THREAD

**Issue by leonardo180** [zachcheatham/ha-omada#18]
Good evening and sorry for the inconvenience,
I am recently having problems with the integration after updating the Omada controller to version 5.0.30.
I have already tried modification # 17 but sadly it didn't work.

In the logs I get the following error:

```
Logger: homeassistant.config_entries
Source: custom_components/omada/__init__.py:32
First occurred: 19:50:59 (1 occurrences)
Last logged: 19:50:59

Error setting up entry Home Controller: Casa for omada
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/omada/__init__.py", line 32, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

Can anyone help me?
Thanks in advance

**Comment by sogood007** [comment]
I just updated to 5.0.30 but I didn't  find this error.  Is the error persistent (as it only show 1 occurrence in your message)?

**Comment by leonardo180** [comment]
Yes, I have tried configuring several times but without success.
Do you know what it can depend on?

**Comment by zachcheatham** [comment]
Are there any additional errors before the error mentioned?

**Comment by baylanger** [comment]
FYI I did a fresh Omada v5.0.30 install and was able to integrate with hass with no issue.

Have you tried to remove the add-on and re-install?
