### ISSUE TITLE
Unable to install integration with version 0.3

### ISSUE THREAD

**Issue by midnightbomber** [zachcheatham/ha-omada#26]
I installed the repository (selected version 0.3) in HACS but was unable to install the integration as there were no results when I searched for Omada in integrations. I uninstalled and reinstalled version 0.3 restarting HA after each change but nothing changed. I uninstalled 0.3 and installed 0.2.1 and it worked right away. I was able to install the integration and configure for my controller. It picked up my 2 EAP225 units and my ER605 as well. Entities were created and the integration is working so far. I have not upgraded to version 0.3 to see whether the settings remain.
HA version: 2022.3.6

**Comment by tonygauderman** [comment]
Had the same issue with 0.3.0.

**Comment by midnightbomber** [comment]
I just updated my working installation of version 0.2.1 to version 0.3 and the integration failed. I restarted HA and got the error below in the log.

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/omada/controller.py:147
Integration: TP-Link Omada (documentation)
First occurred: 11:06:38 PM (1 occurrences)
Last logged: 11:06:38 PM

Error setting up entry Omada-Home: Default for omada
Traceback (most recent call last):
  File "/config/custom_components/omada/controller.py", line 147, in get_api_controller
    await controller.login()
  File "/config/custom_components/omada/api/controller.py", line 51, in login
    response = await self._controller_request("post", "/login", json=auth)
  File "/config/custom_components/omada/api/controller.py", line 155, in _controller_request
    return await self._request(
  File "/config/custom_components/omada/api/controller.py", line 180, in _request
    async with self._session.request(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/omada/__init__.py", line 32, in async_setup_entry
    await omada_controller.async_setup()
  File "/config/custom_components/omada/controller.py", line 74, in async_setup
    self.api = await get_api_controller(
  File "/config/custom_components/omada/controller.py", line 147, in get_api_controller
    await controller.login()
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 116, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
