### ISSUE TITLE
Unable to connect to service

### ISSUE THREAD

**Issue by sreggy** [zachcheatham/ha-omada#3]
Dear all,
I'm trying to enable integration in HA, but when I configure it I get the error 'Unable to connect to service.'
As *URL* I'm using my controller, HTTPS, link .... like **https://192.168.0.200**, *SIte* in the one configured in the controller, like **Home**, and *Verify SSL* is **checked**.

Is there something of wrong in the above configuration, or I get an issue?

Thanks in advance
Stefano

**Comment by markus84de** [comment]
Hi, I can also not connect to the service. Version 2021.10.6.

From the "home-assistant.log":
2021-10-31 12:22:21 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 198, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 256, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/omada/config_flow.py", line 62, in async_step_user
    controller = await get_api_controller(
  File "/config/custom_components/omada/controller.py", line 160, in get_api_controller
    await controller.login()
  File "/config/custom_components/omada/api/controller.py", line 42, in login
    self.role_type = response["roleType"]
TypeError: 'ClientResponse' object is not subscriptable

**Comment by sreggy** [comment]
Hi,
I did another test with Verify SSL non flagged, following the error:
'''
2021-11-09 10:16:57 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 246, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/omada/config_flow.py", line 62, in async_step_user
    controller = await get_api_controller(
  File "/config/custom_components/omada/controller.py", line 166, in get_api_controller
    await controller.update_ssids()
  File "/config/custom_components/omada/api/controller.py", line 52, in update_ssids
    response = await self._site_request("get", "/setting/ssids")
  File "/config/custom_components/omada/api/controller.py", line 62, in _site_request
    return await self._request(method, url, params=tokened_params, json=json)
  File "/config/custom_components/omada/api/controller.py", line 91, in _request
    self._raiseOnResponseError(response)
  File "/config/custom_components/omada/api/controller.py", line 107, in _raiseOnResponseError
    raise_response_error(response)
  File "/config/custom_components/omada/api/errors.py", line 23, in raise_response_error
    raise OmadaApiException("API Error Code {}: {}".format(response["errorCode"], response["msg"]))
custom_components.omada.api.errors.OmadaApiException: API Error Code -1005: Operation forbidden.
'''

any suggestion?
Thanks in advance
Regards
Stefano

**Comment by GHRRGH** [comment]
For me the issue was that I had to use "Default" as the site, instead of the custom site name I have set.
With this change it worked like a charm :)

**Comment by UnbridledGames** [comment]
Same issue, doesn't matter what I use as the site, Unable to connect to service appears immediately upon clicking sumbit. Its too fast to be getting a response from the server.

**Comment by PeterKalel** [comment]
Hello idem for me
Unable to connect to Omada at 192.168.55.9: Error requesting data from 192.168.55.9/api/v2/login: 192.168.55.9/api/v2/login
Unable to connect to Omada at 192.168.55.9:8043: Error requesting data from 192.168.55.9:8043/api/v2/login: 192.168.55.9:8043/api/v2/login
Unable to connect to Omada at https://192.168.55.9:8043: Error requesting data from https://192.168.55.9:8043/api/v2/login: Cannot connect to host 192.168.55.9:8043 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')]

**Comment by rgutialo** [comment]
Same issue here. I try to uncheck the SSL verification (because my browser shows an error) and I got the same error as @sreggy 

Anyone could solve it?

**Comment by zachcheatham** [comment]
Closing this as it's been stale for over a year. Please let us know if you're still having this issue.

**Comment by ssummer** [comment]
Yes, I still have this issue everytime I restart and have an automation to reload it after a few minutes after startup. Possibly the same issue as:https://github.com/zachcheatham/ha-omada/issues/33StephenOn 1 Nov 2022, at 18:57, Zach Cheatham ***@***.***> wrote:﻿
Closing this as it's been stale for over a year. Please let us know if you're still having this issue.

**Comment by KruseLuds** [comment]
I still have the issue but only intermittently. Reloading the integration almost always fixes it.
