### ISSUE TITLE
Error setting up entry OC200: Default for omada

### ISSUE THREAD

**Issue by chopst1x** [zachcheatham/ha-omada#30]
Hi, unfortantley this fails to load now with the below error, any idea? Thanks.

2022-06-04 21:15:24 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry OC200: Default for omada
Traceback (most recent call last):
File "/config/custom_components/omada/controller.py", line 147, in get_api_controller
await controller.login()
File "/config/custom_components/omada/api/controller.py", line 51, in login
response = await self._controller_request("post", "/login", json=auth)
File "/config/custom_components/omada/api/controller.py", line 155, in _controller_request
return await self._request(
File "/config/custom_components/omada/api/controller.py", line 180, in _request
async with self._session.request(
File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
self._resp = await self._coro
File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
await resp.start(conn)
File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
message, payload = await protocol.read() # type: ignore[union-attr]
File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
await self._waiter
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/omada/__init__.py", line 32, in async_setup_entry
await omada_controller.async_setup()
File "/config/custom_components/omada/controller.py", line 74, in async_setup
self.api = await get_api_controller(
File "/config/custom_components/omada/controller.py", line 147, in get_api_controller
await controller.login()
File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 116, in __exit__
self._do_exit(exc_type)
File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 212, in _do_exit
raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

**Comment by jone9618** [comment]
Hi.  I'm getting this too.  Most, but not all, times I restart HA.
