### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by djtoast** [zachcheatham/ha-omada#7]
Im seeing this error when connecting to omada. 

 This error originated from a custom integration.
Logger: aiohttp.server
Source: custom_components/omada/api/errors.py:23
Integration: TP-Link Omada (documentation)
First occurred: 8:34:13 PM (9 occurrences)
Last logged: 8:44:06 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 198, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 256, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/omada/config_flow.py", line 62, in async_step_user
    controller = await get_api_controller(
  File "/config/custom_components/omada/controller.py", line 166, in get_api_controller
    await controller.update_ssids()
  File "/config/custom_components/omada/api/controller.py", line 52, in update_ssids
    response = await self._site_request("get", "/setting/ssids")
  File "/config/custom_components/omada/api/controller.py", line 62, in _site_request
    return await self._request(method, url, params=tokened_params, json=json)
  File "/config/custom_components/omada/api/controller.py", line 91, in _request
    self._raiseOnResponseError(response)
  File "/config/custom_components/omada/api/controller.py", line 107, in _raiseOnResponseError
    raise_response_error(response)
  File "/config/custom_components/omada/api/errors.py", line 23, in raise_response_error
    raise OmadaApiException("API Error Code {}: {}".format(response["errorCode"], response["msg"]))
custom_components.omada.api.errors.OmadaApiException: API Error Code -1005: Operation forbidden.

**Comment by djtoast** [comment]
Im using a new release of Omada wonder if something needs ajusting .

**Comment by organsnyder** [comment]
Having the same issue with a new Omada installation.

**Comment by zachcheatham** [comment]
Closing this as its been stale for almost a year. If you're still having this issue, please let us know.
