### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by CAP-Team** [zachcheatham/ha-omada#71]
For some time now I get this error:

Logger: homeassistant
Source: custom_components/omada/api/controller.py:220
Integration: TP-Link Omada ([documentation](https://github.com/zachcheatham/ha-omada))
First occurred: 09:42:54 (7 occurrences)
Last logged: 09:54:54

**Error doing job: Task exception was never retrieved**
Traceback (most recent call last):
  File "/config/custom_components/omada/controller.py", line 161, in async_update
    await self.api.login()
  File "/config/custom_components/omada/api/controller.py", line 51, in login
    await self._update_api_info()
  File "/config/custom_components/omada/api/controller.py", line 68, in _update_api_info
    response = await self._request("get", f"{self.url}/api/info")
  File "/config/custom_components/omada/api/controller.py", line 220, in _request
    raise RequestError(f"Error connecting to {url}: {err}") from None
custom_components.omada.api.errors.RequestError: Error connecting to https://server2022:8043/api/info: Cannot connect to host server2022:8043 ssl:default [Invalid argument]

Omada runs on a server with a self signed certificate.

The integration seems to work though.

**Comment by CAP-Team** [comment]
Problem still persists:

Logger: homeassistant
Source: custom_components/omada/api/controller.py:220
Integration: TP-Link Omada ([documentation](https://github.com/zachcheatham/ha-omada))
First occurred: 21 augustus 2023 om 14:36:05 **(456 occurrences)**
Last logged: 09:56:07

**Error doing job: Task exception was never retrieved**
Traceback (most recent call last):
  File "/config/custom_components/omada/controller.py", line 161, in async_update
    await self.api.login()
  File "/config/custom_components/omada/api/controller.py", line 51, in login
    await self._update_api_info()
  File "/config/custom_components/omada/api/controller.py", line 68, in _update_api_info
    response = await self._request("get", f"{self.url}/api/info")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/omada/api/controller.py", line 220, in _request
    raise RequestError(f"Error connecting to {url}: {err}") from None
custom_components.omada.api.errors.RequestError: Error connecting to https://server2022:8043/api/info: Cannot connect to host server2022:8043 ssl:default [Invalid argument]
