### ISSUE TITLE
Only showing the device connected

### ISSUE THREAD

**Issue by ashoktvm** [zachcheatham/ha-omada#86]
After adding the integration only devices connected are shown. There is no option under EAP devices to control SSID. 

https://imgur.com/vWY40hr

**Comment by fplanque** [comment]
go to home assistant settings > integrations > omada > configure and click "next" so you can enable all features on subsequent config pages.

**Comment by Zylatis** [comment]
Hi I have a similar problem, it only shows the devices connected as entities (whereas i would like something to list # of devices, etc). When i try to configure the integration i don't see any additional options
![ex1](https://github.com/zachcheatham/ha-omada/assets/1456631/38bff47e-1634-47d5-a597-30b95028e821)
![ex2](https://github.com/zachcheatham/ha-omada/assets/1456631/85099315-1c02-4403-b476-7257942f36b4)

EDIT: i found some errors in the HA logs i'm digging through, some related to SSL. I opted to not confirm the SSL connection because it was failing without that disabled - I'm not sure why, i am using the Omada container.

Seeing a bunch of this stuff
```
2024-03-14 00:16:47.261 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry OmadaController: TheVale for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 238, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 183, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
```

**Comment by spry-salt** [comment]
Same. A bunch of switches have disappeared with the latest version.
